### PR TITLE
Removed potential provocation from the read me

### PR DESCRIPTION
**Pull request by Arseny**
I have removed all potentially provocative material from the read me file.

While I do understand the cause completely, I already personally know people who have been turned off of CSON simply because of the read me file alone.

I have replaced the animal rights examples with (hopefully) non-provoking Wikipedia excerpts. These should perfectly demonstrate the capabilities of CSON and the much improved readability when compared to JSON.

I feel we should maybe separate ethics from file formats :-).

### CODE REVIEW

**Comment by balupton** [comment]
If people are offended by links and data, that's on them, not us.

**Comment by Rhys** [comment]
@balupton Isn't this trying to create a new and better standard? You have to see how this could and does easily turn people off. This is file format standardization, it is no place for a moral debate.

**Comment by PingLangYiu** [comment]
@Rhys Agree!

**Comment by balupton** [comment]
There is no moral debate. There is some data.

If that turns people off, that is between them and the data, not us. It is not our responsibility to surpress or censor information one may find troubling.

Furthermore, and regardless, if one is troubled, perhaps one's responsibility is to address the causes of things they find troubling, rather than whining about the dissemination of troubling things. One of these actually prevents the troubling thing, the other ignores it.

This should not be a pull request here, the onus is not ours. The onus is in the minds of the offended, pull request there.

**Comment by Rhys** [comment]
@balupton Maybe "moral debate" is poor wording, but it is dishonest to act like there is no agenda behind that data.

And, yes, I believe as someone developing a standard, it IS your responsibility to try to make sure the standard is actually adopted. Pushing an ethical agenda, and dismissing the fact that people are bothered by it is very counteractive to getting a standard adopted.

**Comment by balupton** [comment]
> And, yes, I believe as someone developing a standard

This project's first release was 2011. I'd say it is developed rather than developing. Originally we used coffee-scripts eval and toString, so I'd argue coffee-script was the standard, now we use  https://github.com/groupon/cson-parser so I'd argue that is the standard; this is just the project that popularised it, our project.

> it IS your responsibility to try to make sure the standard is actually adopted

How are other people's actions my responsibility? Just because someone publishes something, doesn't mean they must force everyone to have it, nor even that everyone should have it.

> Pushing an ethical agenda

You argue like data has an agenda, it doesn't. "the earth revolves around the sun" has no more of a scientific agenda than a religious agenda, how can it, it just is. To act otherwise, is to not be able to seperate objectivity from subjectivity.

> and dismissing the fact that people are bothered by it

Sure, some people will be offended, some people will be provoked, in the same way people were, and in some places still are, by the fact the earth revolves around the sun. Should we pretend the notion of censoring such information to protect such sensitivities is honourable? It isn't.

> very counteractive to getting a standard adopted.

That's not up to us.

**Comment by RobLoach** [comment]
The goal out of this is to demonstrate how to use CSON. It doesn't matter how it does it. What was there was just some quotes from some sites to show CSON usage.

One thing I would be in favour here would be to make it reference a source that is more community-driven, like Wikipedia.

**Comment by Rhys** [comment]
> You argue like data has an agenda, it doesn't. "the earth revolves around the sun" has no more of a scientific agenda than a religious agenda, how can it, it just is. To act otherwise, is to not be able to seperate objectivity from subjectivity.

Facts can still carry an agenda, especially if they are not showing the other side of the data. This is not about this specific set of data, but instead about any and all polarizing data that is simply irrelevant when discussing a standardized data format. It isn't relevant to the product at all and simply turns people away.

Any other polarizing data would be just as bad and carry just as much of an agenda, even if they are facts, such as:

- The amount of gun murders
- The amount of abortions
- The amount of beheadings by a specific religion
- The amount of each type of organ stolen in Moldova.

None of these belong in this repo, and neither does this IMO.

> I'd say it is developed rather than developing.

Whether you are developing or maintaining, CSON adoption is sitll influenced by you and this repository, especially considering this is the first result on Google.

> How are other people's actions my responsibility? Just because someone publishes something, doesn't mean they must force everyone to have it, nor even that everyone should have it.

Fair enough. If you don't care about adoption of your standard, then it really doesn't matter, but if you DO, then I highly suggest you make this change or similar.

> That's not up to us.

But it is influenced by you, and heavily.

**Comment by balupton** [comment]
> Fair enough. If you don't care about adoption of your standard, then it really doesn't matter, but if you DO, then I highly suggest you make this change or similar.

If people use it great, it not, whatever. For things which onus is on us, we will address. The onus to the problem here - people being offended by data - is not on us.

**Comment by balupton** [comment]
Locking. Our stances have been stated, and the only thing left is bike-shedding of opinions. Offence olympics is not something that makes lives better, nor is it a meaningful conversation to have here. If one has an issue with the right to offend, and why it is important, take it up somewhere more meaningful, like the debate floor with the philosophers of the world.

> - The amount of gun murders
> - The amount of abortions
> - The amount of beheadings by a specific religion
> - The amount of each type of organ stolen in Moldova

I'll keep these in mind for future projects.

Let's all get back to more productive things.

**Pull request closed without merging**
