### PR TITLE
Fix "unknown conversion error" on Windows

### PR DESCRIPTION
**Pull request by jingyu9575**
Hi, yesterday I also saw this bug #133 on Windows, which breaks my build environment. 

I do not know how to pass the conversion parameter to `bin.js`, but I think it can be fixed by providing two binary files `cson2json.js` and `json2cson.js`.

Also, it seems this check sometimes gives wrong conversion directions with some filenames on Linux. For example, `json2cson Ericson2jsonline.json` will actually execute `cson2json` instead because of the filename.
```js
process.argv.toString().indexOf('cson2json')
```

Please have a look. Thank you!

### CODE REVIEW

**Comment by balupton** [comment]
https://github.com/bevry/boundation/issues/24 needs to be implemented first otherwise the changes here will be reverted

**Comment by aminya** [comment]
@balupton Well #24 wasn't implemented ever. Any plan to finally merge this and let us use this tool?

**Comment by jingyu9575** [comment]
Lately I've been using `cson2json ${process.platform === 'win32' ? 'cson2json/../' : ''}${source_file}` to workaround that `indexOf`.

**Comment by balupton** [comment]
> @balupton Well, #24 wasn't implemented ever. Any plan to finally merge this and let us use this tool?

As I said, https://github.com/bevry/boundation/issues/24 needs to be implemented, otherwise the changes here will be automatically reverted.

If you wish to put some of your own incentives into my life, then that would be great, otherwise, you can use your incentives to help accomplish your entitlements via say using the submitted PR directly or sending a PR for https://github.com/bevry/boundation/issues/24. Otherwise, please wait.

Everything of @bevry's is done pro-bono in my spare time, and until it is funded well from donations, then it must compete against other life priorities and incentives. Please consider this.

**Pull request closed without merging**
